### ISSUE TITLE
网页版中文别名乱码

### ISSUE THREAD

**Issue by ifastcms** [uplusware/erisemail#3]
chinese alias show messy code.
![tim 20180425211648](https://user-images.githubusercontent.com/16859026/39248248-1d4dd60e-48ce-11e8-8465-753e9470991c.png)

中文别名在网页显示乱码

**Comment by uplusware** [comment]
Fixed. 请删除/var/erisemail/private/cache/下的缓存文件，然后重启erisemaild 和 memcached (如果有)
