### ISSUE TITLE
ubuntu安装过程异常

### ISSUE THREAD

**Issue by codeoflin** [uplusware/erisemail#4]
首先一开始:
![image](https://user-images.githubusercontent.com/45932283/97127445-9cd85300-1774-11eb-9b38-3cb1d53d08c0.png)

通过手工复制这个文件到/usr/lib后,上面的问题解决,但遇到下一个问题:
![image](https://user-images.githubusercontent.com/45932283/97127620-153f1400-1775-11eb-8ada-6dcc7d71d306.png)

**Comment by codeoflin** [comment]
安装教程要apt安装几个库,其中有一个安装不了,如下:
![image](https://user-images.githubusercontent.com/45932283/97127853-baf28300-1775-11eb-921d-ee6ff6b076af.png)
去掉那个包后apt成功
但问题依旧
![image](https://user-images.githubusercontent.com/45932283/97127991-22103780-1776-11eb-8e0d-a9318c0865e9.png)

**Comment by uplusware** [comment]
您好， 你的安装OS是Ubuntu吗？哪个版本？数据库是MariaDB吗？

**Comment by codeoflin** [comment]
os是ubuntu20.4
还没到数据库这一步,安装过程就出了问题.

**Comment by uplusware** [comment]
安装包是在在ubuntu16tls上生成的。所以推荐16tls.如果您在新版本的话，建议下载源代码然后编译安装。
请参考 https://github.com/uplusware/erisemail/wiki/Installation#install-by-source-code
